[2023-11-30 10:51:22] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn inbound conn e84e816032ac0afc 127.0.0.1:62884 failed checkpoint posthandshake: Connected to self
[2023-11-30 10:51:22] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn dyn dial conn e84e816032ac0afc 127.0.0.1:20132 failed checkpoint posthandshake: Connected to self
[2023-11-30 10:51:25] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2023-11-30 10:51:25] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2023-11-30 10:51:25] [warning] synchronization.go:205 dpchain/blockSync.(*SyncProtocal).handleMsg Block synchronization failed: Couldn't Read the next message from the remote peer (5cd640c7377fa8c9b9beeac48be170d6b2b58991641630127d322298fd6878e38932ca20944b045396242b89c89f0d772ea2b335e7298649124ccb30809d91d2), err:EOF

[2023-11-30 10:51:25] [warning] peer.go:208 dpchain/p2p/server.(*Peer).pingLoop heart beate, ping协程退出

[2023-11-30 10:51:25] [error] dial.go:217 dpchain/p2p/server.(*dialTask).Do dial error: dial tcp 127.0.0.1:20131: connect: connection refused
[2023-11-30 10:51:25] [warning] separator.go:272 dpchain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
