[2023-11-30 10:51:20] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn dyn dial conn 66b887bc5559dab7 127.0.0.1:20130 failed checkpoint posthandshake: Connected to self
[2023-11-30 10:51:20] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn inbound conn 66b887bc5559dab7 127.0.0.1:62873 failed checkpoint posthandshake: Connected to self
[2023-11-30 10:51:25] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2023-11-30 10:51:25] [warning] peer.go:208 dpchain/p2p/server.(*Peer).pingLoop heart beate, ping协程退出

[2023-11-30 10:51:25] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2023-11-30 10:51:25] [error] dial.go:217 dpchain/p2p/server.(*dialTask).Do dial error: dial tcp 127.0.0.1:20131: connect: connection refused
[2023-11-30 10:51:25] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2023-11-30 10:51:25] [warning] peer.go:208 dpchain/p2p/server.(*Peer).pingLoop heart beate, ping协程退出

[2023-11-30 10:51:25] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2023-11-30 10:51:25] [error] dial.go:217 dpchain/p2p/server.(*dialTask).Do dial error: dial tcp 127.0.0.1:20132: connect: connection refused
