[2023-11-30 10:47:35] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn inbound conn 5cd640c7377fa8c9 127.0.0.1:61623 failed checkpoint posthandshake: Connected to self
[2023-11-30 10:47:35] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn dyn dial conn 5cd640c7377fa8c9 127.0.0.1:20131 failed checkpoint posthandshake: Connected to self
[2023-11-30 10:47:37] [warning] server.go:564 dpchain/p2p/server.(*Server).encHandshakeChecks 进行加密handshake: 节点已经与本机建立了连接

[2023-11-30 10:47:37] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn dyn dial conn a237ee4edef0f190 127.0.0.1:20133 failed checkpoint posthandshake: Already connected
