[2023-12-13 17:14:03] [info] server.go:602 dpchain/p2p/server.(*Server).listenLoop 接收到来自节点 127.0.0.1:61391的p2p连接请求

[2023-12-13 17:14:03] [info] server.go:616 dpchain/p2p/server.(*Server).setupConn p2pServer等待完成与目标节点(127.0.0.1:61391)的加密handshake与协议handshake!

[2023-12-13 17:14:03] [info] server.go:616 dpchain/p2p/server.(*Server).setupConn p2pServer等待完成与目标节点(127.0.0.1:20134)的加密handshake与协议handshake!

[2023-12-13 17:14:03] [info] server.go:636 dpchain/p2p/server.(*Server).setupConn p2pServer完成与目标节点(127.0.0.1:61391)的加密handshake!

[2023-12-13 17:14:03] [info] server.go:643 dpchain/p2p/server.(*Server).setupConn 下面进行加密handshake的 checkpoint!!! ,127.0.0.1:61391 

[2023-12-13 17:14:03] [info] server.go:636 dpchain/p2p/server.(*Server).setupConn p2pServer完成与目标节点(127.0.0.1:20134)的加密handshake!

[2023-12-13 17:14:03] [info] server.go:643 dpchain/p2p/server.(*Server).setupConn 下面进行加密handshake的 checkpoint!!! ,127.0.0.1:20134 

[2023-12-13 17:14:03] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn inbound conn 99d430df88c82261 127.0.0.1:61391 failed checkpoint posthandshake: Connected to self
[2023-12-13 17:14:03] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn dyn dial conn 99d430df88c82261 127.0.0.1:20134 failed checkpoint posthandshake: Connected to self
[2023-12-13 17:14:35] [info] server.go:602 dpchain/p2p/server.(*Server).listenLoop 接收到来自节点 127.0.0.1:61598的p2p连接请求

[2023-12-13 17:14:35] [info] server.go:616 dpchain/p2p/server.(*Server).setupConn p2pServer等待完成与目标节点(127.0.0.1:61598)的加密handshake与协议handshake!

[2023-12-13 17:14:35] [info] server.go:616 dpchain/p2p/server.(*Server).setupConn p2pServer等待完成与目标节点(127.0.0.1:20134)的加密handshake与协议handshake!

[2023-12-13 17:14:35] [info] server.go:636 dpchain/p2p/server.(*Server).setupConn p2pServer完成与目标节点(127.0.0.1:61598)的加密handshake!

[2023-12-13 17:14:35] [info] server.go:643 dpchain/p2p/server.(*Server).setupConn 下面进行加密handshake的 checkpoint!!! ,127.0.0.1:61598 

[2023-12-13 17:14:35] [info] server.go:636 dpchain/p2p/server.(*Server).setupConn p2pServer完成与目标节点(127.0.0.1:20134)的加密handshake!

[2023-12-13 17:14:35] [info] server.go:643 dpchain/p2p/server.(*Server).setupConn 下面进行加密handshake的 checkpoint!!! ,127.0.0.1:20134 

[2023-12-13 17:14:35] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn dyn dial conn 99d430df88c82261 127.0.0.1:20134 failed checkpoint posthandshake: Connected to self
[2023-12-13 17:14:35] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn inbound conn 99d430df88c82261 127.0.0.1:61598 failed checkpoint posthandshake: Connected to self
[2023-12-13 17:14:37] [info] dper.go:234 dpchain/ginHttp/router/api.InitRouter.BackAccountList.func16 Http: Get user request -- BackAccountList

[2023-12-13 17:14:37] [info] dper.go:244 dpchain/ginHttp/router/api.InitRouter.BackAccountList.func16 Http: Reply to user request -- BackAccountList  succeed!

[2023-12-13 17:14:37] [info] dper.go:286 dpchain/ginHttp/router/api.InitRouter.UseAccount.func18 Http: Get user request -- UseAccount  account:724e28b038d3a7d3155b2d00cbb7b733ffba4273

[2023-12-13 17:14:38] [info] dper.go:302 dpchain/ginHttp/router/api.InitRouter.UseAccount.func18 Http: Reply to user request -- UseAccount  succeed!

[2023-12-13 17:14:38] [info] dper.go:331 dpchain/ginHttp/router/api.InitRouter.OpenTxCheckMode.func20 Http: Get user request -- OpenTxCheckMode  mode:on

[2023-12-13 17:14:38] [info] dperCommand.go:379 dpchain/dper/client/commandLine.(*CommandLine).handleTxCheckMode Dper: handleTxCheckMode runs successfully, The current Tx check mode is on

[2023-12-13 17:14:38] [info] dper.go:342 dpchain/ginHttp/router/api.InitRouter.OpenTxCheckMode.func20 Http: Reply to user request -- OpenTxCheckMode  succeed!

