[2023-12-08 01:01:02] [info] server.go:616 dpchain/p2p/server.(*Server).setupConn p2pServer等待完成与目标节点(127.0.0.1:20132)的加密handshake与协议handshake!

[2023-12-08 01:01:02] [info] server.go:602 dpchain/p2p/server.(*Server).listenLoop 接收到来自节点 127.0.0.1:56457的p2p连接请求

[2023-12-08 01:01:02] [info] server.go:616 dpchain/p2p/server.(*Server).setupConn p2pServer等待完成与目标节点(127.0.0.1:56457)的加密handshake与协议handshake!

[2023-12-08 01:01:02] [info] server.go:636 dpchain/p2p/server.(*Server).setupConn p2pServer完成与目标节点(127.0.0.1:56457)的加密handshake!

[2023-12-08 01:01:02] [info] server.go:643 dpchain/p2p/server.(*Server).setupConn 下面进行加密handshake的 checkpoint!!! ,127.0.0.1:56457 

[2023-12-08 01:01:02] [info] server.go:636 dpchain/p2p/server.(*Server).setupConn p2pServer完成与目标节点(127.0.0.1:20132)的加密handshake!

[2023-12-08 01:01:02] [info] server.go:643 dpchain/p2p/server.(*Server).setupConn 下面进行加密handshake的 checkpoint!!! ,127.0.0.1:20132 

[2023-12-08 01:01:02] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn inbound conn f4124d176a5f5f8c 127.0.0.1:56457 failed checkpoint posthandshake: Connected to self
[2023-12-08 01:01:02] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn dyn dial conn f4124d176a5f5f8c 127.0.0.1:20132 failed checkpoint posthandshake: Connected to self
[2023-12-08 01:01:08] [info] dper.go:182 dpchain/ginHttp/router/api.InitRouter.UseAccount.func17 Http: Get user request -- UseAccount  account:f5bd17415c467039a442e9a5c871a74c819cd97a

[2023-12-08 01:01:08] [warning] account_manager.go:234 dpchain/accounts.(*Manager).GetAccount Account Manager: The account (f5bd17415c467039a442e9a5c871a74c819cd97a) can't be found!

[2023-12-08 01:01:08] [warning] dper.go:192 dpchain/ginHttp/router/api.InitRouter.UseAccount.func17 Http: Reply to user request -- UseAccount  warn:account with address: f5bd17415c467039a442e9a5c871a74c819cd97a cannot load, no such account is found

[2023-12-08 01:01:34] [info] server.go:616 dpchain/p2p/server.(*Server).setupConn p2pServer等待完成与目标节点(127.0.0.1:20132)的加密handshake与协议handshake!

[2023-12-08 01:01:34] [info] server.go:602 dpchain/p2p/server.(*Server).listenLoop 接收到来自节点 127.0.0.1:56590的p2p连接请求

[2023-12-08 01:01:34] [info] server.go:616 dpchain/p2p/server.(*Server).setupConn p2pServer等待完成与目标节点(127.0.0.1:56590)的加密handshake与协议handshake!

[2023-12-08 01:01:34] [info] server.go:636 dpchain/p2p/server.(*Server).setupConn p2pServer完成与目标节点(127.0.0.1:56590)的加密handshake!

[2023-12-08 01:01:34] [info] server.go:643 dpchain/p2p/server.(*Server).setupConn 下面进行加密handshake的 checkpoint!!! ,127.0.0.1:56590 

[2023-12-08 01:01:34] [info] server.go:636 dpchain/p2p/server.(*Server).setupConn p2pServer完成与目标节点(127.0.0.1:20132)的加密handshake!

[2023-12-08 01:01:34] [info] server.go:643 dpchain/p2p/server.(*Server).setupConn 下面进行加密handshake的 checkpoint!!! ,127.0.0.1:20132 

[2023-12-08 01:01:34] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn inbound conn f4124d176a5f5f8c 127.0.0.1:56590 failed checkpoint posthandshake: Connected to self
[2023-12-08 01:01:34] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn dyn dial conn f4124d176a5f5f8c 127.0.0.1:20132 failed checkpoint posthandshake: Connected to self
[2023-12-08 01:01:51] [info] dper.go:130 dpchain/ginHttp/router/api.InitRouter.BackAccountList.func15 Http: Get user request -- BackAccountList

[2023-12-08 01:01:51] [info] dper.go:140 dpchain/ginHttp/router/api.InitRouter.BackAccountList.func15 Http: Reply to user request -- BackAccountList  succeed!

