[2023-12-14 10:55:52] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn inbound conn 04d9d9f799e09700 127.0.0.1:55502 failed checkpoint posthandshake: Connected to self
[2023-12-14 10:55:52] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn dyn dial conn 04d9d9f799e09700 127.0.0.1:20134 failed checkpoint posthandshake: Connected to self
[2023-12-14 10:55:52] [warning] server.go:564 dpchain/p2p/server.(*Server).encHandshakeChecks 进行加密handshake: 节点已经与本机建立了连接

[2023-12-14 10:55:52] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn inbound conn 13229046edacba0b 127.0.0.1:55505 failed checkpoint posthandshake: Already connected
